# Generated by Django 4.2.11 on 2024-05-17 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='AudioSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_name', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='music/')),
                ('audio_img', models.FileField(upload_to='music_pic/')),
                ('audio_genre', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='audioPlayerApi.genre')),
            ],
        ),
    ]
