# Generated by Django 4.2.11 on 2024-05-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioPlayerApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
    ]
