# Generated by Django 4.2.11 on 2024-05-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioPlayerApi', '0002_alter_genre_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosongs',
            name='audio_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='audiosongs',
            name='audio_img',
            field=models.FileField(upload_to=''),
        ),
    ]
