# Generated by Django 4.2.11 on 2024-05-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioPlayerApi', '0003_alter_audiosongs_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosongs',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='audiosongs',
            name='audio_img',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
